var async = require('async');
let dbCreds = require('./dbCreds.js');
const data = require('../output/parsedAA.json');

let meetingTimes = [];

//add ids, create meetings array
data.forEach((d, i) => {
  d.groupId = i;
  if (!d.accessibility) {
    d.accessibility = 0;
  }
  d.meetings.forEach((z, j) => {
    z.groupId = i;
    meetingTimes.push(z);
  });
});

meetingTimes.forEach((d, i) => (d.id = i));

let client = dbCreds.client;
client.connect();

function writeMeetings() {
  async.each(meetingTimes, async function (value, callback) {
    console.log('running');
    let query;
    if (value.specialInterest) {
      query = `INSERT INTO meetingTimes(id, groupId, day, specialInterest, starttime, endtime) VALUES ( ${value.id}, ${value.groupId}, '${value.day}', null, '${value.startTime}', '${value.endTime}' )`;
    } else {
      query = `INSERT INTO meetingTimes(id, groupId, day, specialInterest, starttime, endtime) VALUES ( ${value.id}, ${value.groupId}, '${value.day}', '${value.specialInterest}', '${value.startTime}', '${value.endTime}' )`;
    }
    await client.query(query, (err, res) => {
      console.log(err, res);
    });
    return;
    //setTimeout(callback, 1000);
  });
}

async function querySelectAll(tableName) {
  let query = `select * from ${tableName}`;
  let queryRes = await client.query(query, (err, res) => {
    console.log(err, res.rows);
    client.end();
    return res;
  });
  //console.log(queryRes.rowCount);
  return queryRes;
}

//INSERT MEETING TIMES
//writeMeetings();
// querySelectAll('meetingTimes');

//INSERT MEETING GROUPS

//   'CREATE TABLE aaGroups (id int GENERATED BY DEFAULT AS IDENTITY, buildingName varchar(100), groupName varchar(100), location varchar(100), details varchar(2555), accessibility boolean, latitude double precision, long double precision );';

async function writeGroups() {
  console.log(data[0]);
  await async.each(data, async function (value, callback) {
    console.log('running');
    let query;
    query = `INSERT INTO aaGroups(id, buildingName, groupName, location, details, accessibility, latitude, long) VALUES ( ${value.groupId}, '${value.buildingName}', '${value.groupName}', '${value.location}',  '${value.details}', '${value.accessibility}' , '${value.latitude}', '${value.longitude}')`;

    console.log(query);

    await client.query(query, (err, res) => {
      console.log(err, res);
    });
    return;
  });

  return;
}

// writeGroups();
console.log(data.length);
querySelectAll('aaGroups');
